name: Caller Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-docker-build:
    uses: ./.github/workflows/docker-build-push.yml
    with:
      image_name: my-app
      tag: latest
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      
