name: Reusable Build Workflow

on:
  workflow_call:   

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run a sample script
        run: echo "Hello from reusable workflow!"
        
